edition = "2024"
style_edition = "2024"
unstable_features = true

fn_call_width = 40
hex_literal_case = "Upper"
max_width = 80
newline_style = "Unix"
struct_lit_width = 0
struct_variant_width = 0
use_field_init_shorthand = true

color = "Always"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
doc_comment_code_block_small_heuristics = "Default"
format_macro_matchers = false
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
wrap_comments = true
