//! Ocean maps as compile-time data.
//!
//! A map is one ocean's league-point graph as drawn on its yppedia map
//! template: league points at grid cells, the leagues joining neighbouring
//! ones, and the islands and archipelago labels among them. An island always
//! sits on a league point; the points in between are open sea. A chart, in
//! game terms, is one route between two neighbouring islands - the run of
//! league points from one to the next - and a map is the collection of them.
//!
//! `x` grows east and `y` grows south. A league joins two points that are
//! either two columns apart on one row (east-west) or one column and one row
//! apart (a diagonal), so every point reachable on a map shares the parity of
//! `x + y`, and a point is never found in the middle of an east-west league.
//! Two points that close - a single league apart - can be sailed between,
//! whether or not a chart covers the route.
//!
//! The data itself is generated by `build.rs` from `src/data/maps/*.json`
//! (see `scripts/extract_map.py` for how a map file is produced), so nothing
//! here is parsed at run time. A map file holds only the leagues the wiki's
//! map draws, which are the charted ones; the leagues no chart follows are
//! filled in from the geometry by `build.rs` and marked
//! [`Chart::Nonexistent`]. The cursor sails those like any other, but the
//! map is drawn as the wiki draws it, so they are left out of the drawing
//! until both their ends are memorized.

use std::collections::BTreeSet;

/// A grid cell on a map: `(x, y)`.
pub type Point = (u16, u16);

/// A compass heading along the league grid. There are no north-south leagues.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Heading {
    E,
    W,
    Ne,
    Nw,
    Se,
    Sw,
}

impl Heading {
    /// Short compass label, e.g. `"NE"`.
    pub fn label(self) -> &'static str {
        match self {
            Heading::E => "E",
            Heading::W => "W",
            Heading::Ne => "NE",
            Heading::Nw => "NW",
            Heading::Se => "SE",
            Heading::Sw => "SW",
        }
    }

    pub fn opposite(self) -> Heading {
        match self {
            Heading::E => Heading::W,
            Heading::W => Heading::E,
            Heading::Ne => Heading::Sw,
            Heading::Nw => Heading::Se,
            Heading::Se => Heading::Nw,
            Heading::Sw => Heading::Ne,
        }
    }

    /// The cell one league away in this heading, or `None` off the grid.
    pub fn step(self, (x, y): Point) -> Option<Point> {
        let (dx, dy): (i16, i16) = match self {
            Heading::E => (2, 0),
            Heading::W => (-2, 0),
            Heading::Ne => (1, -1),
            Heading::Nw => (-1, -1),
            Heading::Se => (1, 1),
            Heading::Sw => (-1, 1),
        };
        Some((
            x.checked_add_signed(dx)?,
            y.checked_add_signed(dy)?,
        ))
    }
}

/// A named cell: an island, or an archipelago label.
pub struct Place {
    pub name: &'static str,
    pub x: u16,
    pub y: u16,
}

impl Place {
    pub fn at(&self) -> Point {
        (self.x, self.y)
    }
}

/// How a league's chart can be had. The first two are the line styles the
/// yppedia map draws; the third is a league it does not draw at all.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Chart {
    /// Sold in game. Drawn as a solid line.
    Sold,
    /// Not sold anywhere: a chart for it drops as booty. Drawn dotted.
    Booty,
    /// There is none, because no charted route runs this way. The league is
    /// sailable all the same, from memory of both its ends.
    Nonexistent,
}

/// One league between two neighbouring points. Each league is listed once,
/// from its western point, so `heading` is only ever `E`, `Se` or `Ne`.
pub struct League {
    pub x: u16,
    pub y: u16,
    pub heading: Heading,
    pub chart: Chart,
}

impl League {
    /// Both ends, western first.
    pub fn ends(&self) -> (Point, Point) {
        let from = (self.x, self.y);
        let to = self
            .heading
            .step(from)
            .expect("league endpoints are checked by build.rs");
        (from, to)
    }

    /// The far end when leaving `from` along `heading`, if that runs along
    /// this league.
    pub fn follow(&self, from: Point, heading: Heading) -> Option<Point> {
        let (a, b) = self.ends();
        if from == a && heading == self.heading {
            Some(b)
        } else if from == b && heading == self.heading.opposite() {
            Some(a)
        } else {
            None
        }
    }
}

/// One ocean's map.
pub struct Map {
    /// Ocean name as [`crate::ocean::Ocean::name`] spells it.
    pub ocean: &'static str,
    /// The yppedia page the map was extracted from.
    #[allow(dead_code)] // attribution, kept with the data
    pub source: &'static str,
    pub islands: &'static [Place],
    /// Archipelago names, placed where the map shows them.
    pub labels: &'static [Place],
    pub leagues: &'static [League],
}

impl Map {
    /// The map of an ocean, by (case-insensitive) name, if one is compiled
    /// in.
    pub fn for_ocean(name: &str) -> Option<&'static Map> {
        MAPS.iter().find(|m| m.ocean.eq_ignore_ascii_case(name))
    }

    pub fn island_at(&self, p: Point) -> Option<&'static Place> {
        self.islands.iter().find(|i| i.at() == p)
    }

    /// The point reached by sailing one league from `from` along `heading`,
    /// with the league taken.
    pub fn neighbour(
        &self,
        from: Point,
        heading: Heading,
    ) -> Option<(Point, &'static League)> {
        self.leagues
            .iter()
            .find_map(|l| l.follow(from, heading).map(|to| (to, l)))
    }

    /// Every league leaving `p`, as (heading away from `p`, far end, league).
    pub fn leagues_at(
        &self,
        p: Point,
    ) -> impl Iterator<Item = (Heading, Point, &'static League)> {
        self.leagues.iter().filter_map(move |l| {
            let (a, b) = l.ends();
            if a == p {
                Some((l.heading, b, l))
            } else if b == p {
                Some((l.heading.opposite(), a, l))
            } else {
                None
            }
        })
    }

    /// Every league point on the map: each league end, plus each island
    /// (an island always sits on a league point, so this only matters for
    /// an island with no league at all).
    pub fn points(&self) -> BTreeSet<Point> {
        self.leagues
            .iter()
            .flat_map(|l| {
                let (a, b) = l.ends();
                [a, b]
            })
            .chain(self.islands.iter().map(Place::at))
            .collect()
    }

    /// The nearest league point lying beyond `from` in the direction `step`
    /// points — east or west of it for a sideways step, south or north for an
    /// upright one.
    ///
    /// This is what a scrollbar's arrow asks for. It cannot ask by grid square:
    /// points sit several squares apart, so one square along lands in open
    /// water, whose nearest point is the one the cursor is already on — an
    /// arrow that asked that way would never move at all.
    pub fn next_point_along(
        &self,
        from: Point,
        step: (i32, i32),
    ) -> Option<Point> {
        let beyond = |p: Point| {
            let (dx, dy) = (
                i32::from(p.0) - i32::from(from.0),
                i32::from(p.1) - i32::from(from.1),
            );
            // The step is along one axis; a point counts as beyond `from` when
            // it lies that way along it, whatever it does on the other.
            0 < dx * step.0 + dy * step.1
        };
        // Drifting across the step costs more than travelling along it, so a
        // step keeps to the row or column it started in where that row or
        // column holds a point at all. Without the weight the nearest
        // point north is usually the diagonal one, and a few steps
        // north walk sideways across the ocean.
        const ACROSS: i64 = 4;
        self.points().into_iter().filter(|&p| beyond(p)).min_by_key(
            |&(x, y)| {
                let dx = i64::from(x) - i64::from(from.0);
                let dy = i64::from(y) - i64::from(from.1);
                let (along, across) =
                    if step.0 == 0 { (dy, dx) } else { (dx, dy) };
                along * along + ACROSS * across * across
            },
        )
    }

    /// The league point nearest `target` in grid space, or `None` on a map with
    /// no points at all.
    ///
    /// The scrollbars point at a place on the chart rather than at a point, and
    /// the cursor only ever sits on a point, so what they ask for is snapped
    /// here. Distance is squared Euclidean in grid steps, which keeps a point
    /// one square away on either axis nearer than one two squares off on
    /// either; ties go to the first in map order.
    pub fn nearest_point(&self, target: Point) -> Option<Point> {
        self.points().into_iter().min_by_key(|&(x, y)| {
            let dx = i64::from(x) - i64::from(target.0);
            let dy = i64::from(y) - i64::from(target.1);
            dx * dx + dy * dy
        })
    }

    /// The largest `x` and `y` anything on the map occupies.
    pub fn extent(&self) -> Point {
        self.points()
            .into_iter()
            .chain(self.labels.iter().map(Place::at))
            .fold((0, 0), |(mx, my), (x, y)| {
                (mx.max(x), my.max(y))
            })
    }
}

/// Every map compiled in, generated by `build.rs`.
pub static MAPS: &[Map] = include!(concat!(env!("OUT_DIR"), "/maps.rs"));

#[cfg(test)]
mod tests {
    use super::{Chart, Heading, MAPS, Map};

    /// Any two league points a single league apart can be sailed between, so
    /// the compiled graph joins them whether or not a chart does. The wiki's
    /// map draws only the charted leagues; `build.rs` derives the rest.
    #[test]
    fn points_a_league_apart_are_joined() {
        for map in MAPS {
            let points = map.points();
            for &from in &points {
                for heading in [Heading::E, Heading::Se, Heading::Ne] {
                    let Some(to) = heading.step(from) else {
                        continue;
                    };
                    if !points.contains(&to) {
                        continue;
                    }
                    // an east-west league spans two columns, and one that
                    // would cross a point is no league at all
                    let crossed = (from.0 + 1, from.1);
                    if heading == Heading::E && points.contains(&crossed) {
                        continue;
                    }
                    assert!(
                        map.neighbour(from, heading).is_some(),
                        "{}: {from:?} and {to:?} are one league apart but \
                         have no league",
                        map.ocean
                    );
                }
            }
        }
    }

    /// No east-west league passes over a league point, or the cursor could
    /// sail past a point without ever stopping on it.
    #[test]
    fn no_league_crosses_a_point() {
        for map in MAPS {
            let points = map.points();
            for league in map.leagues {
                if league.heading != Heading::E {
                    continue;
                }
                let crossed = (league.x + 1, league.y);
                assert!(
                    !points.contains(&crossed),
                    "{}: the league east of {:?} crosses {crossed:?}",
                    map.ocean,
                    (league.x, league.y)
                );
            }
        }
    }

    /// Every live ocean has a map compiled in.
    #[test]
    fn every_live_ocean_has_a_map() {
        for ocean in crate::ocean::Ocean::LIVE {
            assert!(
                Map::for_ocean(ocean.name()).is_some(),
                "{} has no map",
                ocean.name()
            );
        }
    }

    /// Every island on a map is in the embedded geography under the same
    /// name. The island column looks the cursor's island up there, so a
    /// name that drifts apart would quietly leave the column empty.
    #[test]
    fn every_island_on_a_map_is_in_the_geography() {
        for map in MAPS {
            let geography = crate::bare::BARE
                .ocean(map.ocean)
                .unwrap_or_else(|| panic!("{} geography", map.ocean));
            for island in map.islands {
                assert!(
                    geography.island(island.name).is_some(),
                    "{}: {} is on the map but not in the geography",
                    map.ocean,
                    island.name
                );
            }
        }
    }

    /// A scrollbar's arrow asks for the next point along an axis, and must
    /// actually get one: a point sits several grid squares from its
    /// neighbours, so an ask that stepped one square and snapped back would
    /// land on the point it started from and the arrow would be dead.
    #[test]
    fn a_step_along_an_axis_reaches_a_further_point() {
        // One ocean is enough: what is being checked is the geometry of a step,
        // not any one map's layout.
        for map in [Map::for_ocean("Emerald").expect("Emerald map")] {
            let points = map.points();
            for &from in &points {
                for step in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
                    let Some(to) = map.next_point_along(from, step) else {
                        continue; // nothing that way at all
                    };
                    assert_ne!(
                        to, from,
                        "{}: a step {step:?} from {from:?} stayed put",
                        map.ocean
                    );
                    let (dx, dy) = (
                        i32::from(to.0) - i32::from(from.0),
                        i32::from(to.1) - i32::from(from.1),
                    );
                    assert!(
                        0 < dx * step.0 + dy * step.1,
                        "{}: a step {step:?} from {from:?} went to {to:?}",
                        map.ocean
                    );
                }
            }
        }
    }

    /// Two charted routes can reach one island from points that are
    /// themselves a league apart, and that league is sailable without either
    /// chart: the approaches to Ashkelon Arch from Morannon Island to its
    /// west and Kashgar Island to its south are the case in point.
    #[test]
    fn the_approaches_to_an_island_are_joined() {
        let map = Map::for_ocean("Emerald").expect("Emerald map");
        let (to, league) = map
            .neighbour((17, 50), Heading::Se)
            .expect("west and south-west approaches to Ashkelon Arch");
        assert_eq!(to, (18, 51));
        assert_eq!(league.chart, Chart::Nonexistent);
    }
}
