//! Ocean maps as compile-time data.
//!
//! A map is one ocean's league-point graph as drawn on its yppedia map
//! template: league points at grid cells, the leagues joining neighbouring
//! ones, and the islands and archipelago labels among them. An island always
//! sits on a league point; the points in between are open sea. A chart, in
//! game terms, is one route between two neighbouring islands - the run of
//! league points from one to the next - and a map is the collection of them.
//!
//! `x` grows east and `y` grows south. A league joins two points that are
//! either two columns apart on one row (east-west) or one column and one row
//! apart (a diagonal), so every point reachable on a map shares the parity of
//! `x + y`, and a point is never found in the middle of an east-west league.
//!
//! The data itself is generated by `build.rs` from `src/data/maps/*.json`
//! (see `scripts/extract_map.py` for how a map file is produced), so nothing
//! here is parsed at run time.

use std::collections::BTreeSet;

/// A grid cell on a map: `(x, y)`.
pub type Point = (u16, u16);

/// A compass heading along the league grid. There are no north-south leagues.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Heading {
    E,
    W,
    Ne,
    Nw,
    Se,
    Sw,
}

impl Heading {
    /// Short compass label, e.g. `"NE"`.
    pub fn label(self) -> &'static str {
        match self {
            Heading::E => "E",
            Heading::W => "W",
            Heading::Ne => "NE",
            Heading::Nw => "NW",
            Heading::Se => "SE",
            Heading::Sw => "SW",
        }
    }

    pub fn opposite(self) -> Heading {
        match self {
            Heading::E => Heading::W,
            Heading::W => Heading::E,
            Heading::Ne => Heading::Sw,
            Heading::Nw => Heading::Se,
            Heading::Se => Heading::Nw,
            Heading::Sw => Heading::Ne,
        }
    }

    /// The cell one league away in this heading, or `None` off the grid.
    pub fn step(self, (x, y): Point) -> Option<Point> {
        let (dx, dy): (i16, i16) = match self {
            Heading::E => (2, 0),
            Heading::W => (-2, 0),
            Heading::Ne => (1, -1),
            Heading::Nw => (-1, -1),
            Heading::Se => (1, 1),
            Heading::Sw => (-1, 1),
        };
        Some((
            x.checked_add_signed(dx)?,
            y.checked_add_signed(dy)?,
        ))
    }
}

/// A named cell: an island, or an archipelago label.
pub struct Place {
    pub name: &'static str,
    pub x: u16,
    pub y: u16,
}

impl Place {
    pub fn at(&self) -> Point {
        (self.x, self.y)
    }
}

/// One league between two neighbouring points. Each league is listed once,
/// from its western point, so `heading` is only ever `E`, `Se` or `Ne`.
/// `solid` is the line style on the yppedia map: a solid league lies on a
/// route whose chart is sold in game; a dotted one's chart is not sold and
/// only drops as booty.
pub struct League {
    pub x: u16,
    pub y: u16,
    pub heading: Heading,
    pub solid: bool,
}

impl League {
    /// Both ends, western first.
    pub fn ends(&self) -> (Point, Point) {
        let from = (self.x, self.y);
        let to = self
            .heading
            .step(from)
            .expect("league endpoints are checked by build.rs");
        (from, to)
    }

    /// The far end when leaving `from` along `heading`, if that runs along
    /// this league.
    pub fn follow(&self, from: Point, heading: Heading) -> Option<Point> {
        let (a, b) = self.ends();
        if from == a && heading == self.heading {
            Some(b)
        } else if from == b && heading == self.heading.opposite() {
            Some(a)
        } else {
            None
        }
    }
}

/// One ocean's map.
pub struct Map {
    /// Ocean name as [`crate::ocean::Ocean::name`] spells it.
    pub ocean: &'static str,
    /// The yppedia page the map was extracted from.
    #[allow(dead_code)] // attribution, kept with the data
    pub source: &'static str,
    pub islands: &'static [Place],
    /// Archipelago names, placed where the map shows them.
    pub labels: &'static [Place],
    pub leagues: &'static [League],
}

impl Map {
    /// The map of an ocean, by (case-insensitive) name, if one is compiled
    /// in.
    pub fn for_ocean(name: &str) -> Option<&'static Map> {
        MAPS.iter().find(|m| m.ocean.eq_ignore_ascii_case(name))
    }

    pub fn island_at(&self, p: Point) -> Option<&'static Place> {
        self.islands.iter().find(|i| i.at() == p)
    }

    /// The point reached by sailing one league from `from` along `heading`,
    /// with the league taken.
    pub fn neighbour(
        &self,
        from: Point,
        heading: Heading,
    ) -> Option<(Point, &'static League)> {
        self.leagues
            .iter()
            .find_map(|l| l.follow(from, heading).map(|to| (to, l)))
    }

    /// Every league leaving `p`, as (heading away from `p`, far end, league).
    pub fn leagues_at(
        &self,
        p: Point,
    ) -> impl Iterator<Item = (Heading, Point, &'static League)> {
        self.leagues.iter().filter_map(move |l| {
            let (a, b) = l.ends();
            if a == p {
                Some((l.heading, b, l))
            } else if b == p {
                Some((l.heading.opposite(), a, l))
            } else {
                None
            }
        })
    }

    /// Every league point on the map: each league end, plus each island
    /// (an island always sits on a league point, so this only matters for
    /// an island with no league at all).
    pub fn points(&self) -> BTreeSet<Point> {
        self.leagues
            .iter()
            .flat_map(|l| {
                let (a, b) = l.ends();
                [a, b]
            })
            .chain(self.islands.iter().map(Place::at))
            .collect()
    }

    /// The largest `x` and `y` anything on the map occupies.
    pub fn extent(&self) -> Point {
        self.points()
            .into_iter()
            .chain(self.labels.iter().map(Place::at))
            .fold((0, 0), |(mx, my), (x, y)| {
                (mx.max(x), my.max(y))
            })
    }
}

/// Every map compiled in, generated by `build.rs`.
pub static MAPS: &[Map] = include!(concat!(env!("OUT_DIR"), "/maps.rs"));
